import Foundation

/// Turns the provider/channel choices in a `BuilderDraft` into a
/// `.env.example` file the user can either paste into their shell or
/// drop into `~/.openclaw/` directly. This is the GUI → dotfile bridge.
///
/// By default we *never* write real secret values into the generated
/// file. That way the file is safe to commit alongside a workspace and
/// safe to share with a collaborator. The user has to tick
/// `includeKeysInGeneratedEnv` to opt into baking real keys in.
enum EnvFileGenerator {
    static func render(from draft: BuilderDraft) -> String {
        var lines: [String] = [
            "# Generated by CLAW AGENT BUILDER",
            "# Edit values below and move this file to `.env` (drop the .example) to load it.",
            "# Safe-by-default: real keys are only baked in when you opted in explicitly.",
            ""
        ]

        let enabledProviders = ModelProviderCatalog.all.filter {
            draft.enabledProviderIDs.contains($0.id)
        }
        if !enabledProviders.isEmpty {
            lines.append("# --- Model providers ---")
            for provider in enabledProviders {
                lines.append("# \(provider.title): \(provider.tagline)")
                lines.append("# Get a key: \(provider.signupURL)")
                let value = valueFor(envKey: provider.envKey, draft: draft)
                lines.append("\(provider.envKey)=\(value)")
                lines.append("")
            }
        }

        let enabledSecrets = ChannelSecretCatalog.all.filter {
            draft.enabledChannelSecretIDs.contains($0.id)
        }
        if !enabledSecrets.isEmpty {
            lines.append("# --- Channel bridges ---")
            for secret in enabledSecrets {
                lines.append("# \(secret.title) — \(secret.tagline)")
                lines.append("# Setup: \(secret.signupURL)")
                let value = valueFor(envKey: secret.envKey, draft: draft)
                lines.append("\(secret.envKey)=\(value)")
                lines.append("")
            }
        }

        let enabledPublicAPIs = draft.orderedAPIs.filter { $0.environmentKey != nil }
        if !enabledPublicAPIs.isEmpty {
            lines.append("# --- Public data APIs (from Data Sources) ---")
            for api in enabledPublicAPIs {
                if let envKey = api.environmentKey {
                    lines.append("# \(api.title) — \(api.summary)")
                    lines.append("# Docs: \(api.docsURL)")
                    let value = valueFor(envKey: envKey, draft: draft)
                    lines.append("\(envKey)=\(value)")
                    lines.append("")
                }
            }
        }

        if enabledProviders.isEmpty && enabledSecrets.isEmpty && enabledPublicAPIs.isEmpty {
            lines.append("# No providers or channels enabled yet.")
            lines.append("# Flip one on in API Keys & Providers and this file will fill in.")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    /// Return the blank placeholder unless the user has explicitly
    /// opted into including real keys in the generated file.
    private static func valueFor(envKey: String, draft: BuilderDraft) -> String {
        if draft.includeKeysInGeneratedEnv,
           let value = draft.apiKeyValues[envKey]?.trimmingCharacters(in: .whitespacesAndNewlines),
           !value.isEmpty {
            return quoteIfNeeded(value)
        }
        return ""
    }

    private static func quoteIfNeeded(_ value: String) -> String {
        if value.contains(" ") || value.contains("#") || value.contains("\"") {
            let escaped = value.replacingOccurrences(of: "\"", with: "\\\"")
            return "\"\(escaped)\""
        }
        return value
    }
}
